# Generated by Django 5.2.8 on 2025-12-17 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("url", "0003_alter_url_created_at_alter_url_expiry_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedirectionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for the rule", max_length=255
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=dict,
                        help_text="JSON conditions for when this rule applies",
                    ),
                ),
                (
                    "target_url",
                    models.URLField(
                        help_text="Redirect destination URL when conditions match",
                        max_length=2000,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Rule priority (higher = checked first)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether rule is enabled"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "url",
                    models.ForeignKey(
                        help_text="Associated short URL",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redirection_rules",
                        to="url.url",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["url", "priority"], name="redirection_url_id_edccec_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="redirection_is_acti_919103_idx"
                    ),
                ],
            },
        ),
    ]
