# Generated by Django 5.0.6 on 2024-05-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=1024)),
                ('short_url', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
