# Generated by Django 5.2.8 on 2025-12-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "admin"), ("STAFF", "staff"), ("USER", "user")],
                db_index=True,
                default="USER",
                max_length=32,
            ),
        ),
    ]
