# Generated by Django 5.2.8 on 2025-12-08 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=512, null=True, unique=True
                    ),
                ),
                ("long_url", models.CharField(max_length=2000)),
                ("short_url", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("visits", models.IntegerField(default=0)),
                ("unique_visits", models.IntegerField(default=0)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("is_custom_alias", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UrlStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("flagged", "Flagged"),
                            ("disabled", "Disabled"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "url",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="url_status",
                        to="url.url",
                    ),
                ),
            ],
        ),
    ]
