# Generated by Django 5.2.8 on 2025-11-20 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='is_active',
        ),
        migrations.AddField(
            model_name='url',
            name='unique_visits',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UrlStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('flagged', 'Flagged'), ('disabled', 'Disabled'), ('suspended', 'Suspended')], default='active', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=256, null=True)),
                ('url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='url_status', to='url.url')),
            ],
        ),
    ]
