# Generated by Django 5.2.8 on 2025-12-17 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("url", "0002_alter_urlstatus_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="url",
            name="expiry_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="url",
            name="last_accessed",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="urlstatus",
            name="state",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "active"),
                    ("EXPIRED", "expired"),
                    ("FLAGGED", "flagged"),
                    ("DISABLED", "disabled"),
                    ("SUSPENDED", "suspended"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(
                fields=["user", "created_at"], name="url_url_user_id_dcaa8b_idx"
            ),
        ),
    ]
