# Generated by Django 5.2.8 on 2025-12-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("url", "0003_alter_url_created_at_alter_url_expiry_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="urlstatus",
            name="last_checked",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="urlstatus",
            name="state",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "active"),
                    ("EXPIRED", "expired"),
                    ("FLAGGED", "flagged"),
                    ("DISABLED", "disabled"),
                    ("BROKEN", "broken"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=16,
            ),
        ),
    ]
