# Generated by Django 5.2.8 on 2025-12-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_url_name_alter_url_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='is_custom_alias',
            field=models.BooleanField(default=False),
        ),
    ]
