# Generated by Django 5.2.8 on 2026-01-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("url", "0004_urlstatus_last_checked_alter_urlstatus_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urlstatus",
            name="last_checked",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="urlstatus",
            name="reason",
            field=models.CharField(
                blank=True, db_index=True, max_length=256, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="urlstatus",
            index=models.Index(fields=["state"], name="url_urlstat_state_1491b5_idx"),
        ),
        migrations.AddIndex(
            model_name="urlstatus",
            index=models.Index(
                fields=["last_checked"], name="url_urlstat_last_ch_bfbb03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="urlstatus",
            index=models.Index(
                fields=["state", "last_checked"], name="url_urlstat_state_712041_idx"
            ),
        ),
    ]
