# Generated by Django 5.2.8 on 2026-01-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("url", "0005_alter_urlstatus_last_checked_alter_urlstatus_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="name",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
