# Generated by Django 5.2.8 on 2025-12-14 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='actions',
            new_name='action',
        ),
    ]
