# Generated by Django 5.2.8 on 2025-12-17 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("url", "0003_alter_url_created_at_alter_url_expiry_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FraudIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("burst", "Burst Protection Triggered"),
                            ("throttle", "Throttle Violation"),
                            ("suspicious_ua", "Suspicious User Agent"),
                            ("other", "Other"),
                        ],
                        help_text="Type of fraud incident detected.",
                        max_length=20,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        help_text="JSON details of the incident (e.g., IP, URL, timestamp)."
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        help_text="Severity level of the incident.",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the incident was logged.",
                    ),
                ),
                (
                    "url",
                    models.ForeignKey(
                        blank=True,
                        help_text="URL associated with the incident, if applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="url.url",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User associated with the incident, if applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fraud Incident",
                "verbose_name_plural": "Fraud Incidents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["incident_type"], name="fraud_fraud_inciden_162f25_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="fraud_fraud_created_8a35e3_idx"
                    ),
                    models.Index(
                        fields=["severity"], name="fraud_fraud_severit_415a3d_idx"
                    ),
                ],
            },
        ),
    ]
