"""
Django settings for UrlShortener project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import environ
import os
from datetime import timedelta
from configurations import Configuration

# Build paths inside the project like this: BASE_DIR / 'subdir'.


BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Initialize environment variables

env = environ.Env(
    DATABASE_NAME=(str),
    DATABASE_USER=(str),
    DATABASE_PASSWORD=(str),
    DATABASE_PORT=(str),
    SECRET_KEY=(str),
    DEBUG=(bool, True),
    ENVIRONMENT=(str, "development"),
)
try:
    environ.Env.read_env(str(BASE_DIR / ".env"))
except FileNotFoundError:
    print("Warning: .env file not found. Using environment variables directly.")


class Base(Configuration):
    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY: str = env("SECRET_KEY")

    ALLOWED_CONFIGS_SCHEMA = {
        "rate_limit_ip": {"type": str, "default": "100/hour"},
        "rate_limit_user": {"type": str, "default": "1000/hour"},
        "short_code_length": {"type": int, "default": 8},
        "short_code_pool_size": {"type": int, "default": 10000},
        "jwt_access_token_minutes": {"type": int, "default": 5},
        "analytics_track_ip": {"type": bool, "default": True},
        "max_urls_per_user": {"type": int, "default": 100},
        "url_mapping_cache_timeout": {"type": int, "default": 3600},
    }

    # SECURITY WARNING: don't run with debug turned on in production!
    APP_VERSION = "0.0.1"
    ENVIRONMENT = env("ENVIRONMENT")

    DEBUG: bool = env("DEBUG")

    ALLOWED_HOSTS = []

    # Application definition

    INSTALLED_APPS = [
        "corsheaders",
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        "drf_spectacular",
        "drf_spectacular_sidecar",
        "rest_framework",
        "rest_framework_simplejwt",
        "csp",
        "django_celery_beat",
        "djoser",
        "config",
        "api",
        "api.custom_auth",
        "api.url",
        "api.url.redirection",
        "api.url.link_rot",
        "api.analytics",
        "api.admin_panel",
        "api.admin_panel.system",
        "api.admin_panel.insight",
        "api.admin_panel.fraud",
    ]

    MIDDLEWARE = [
        "django.middleware.security.SecurityMiddleware",
        "csp.middleware.CSPMiddleware",
        "corsheaders.middleware.CorsMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
        "api.middleware.JsonValidationMiddleware",
        "api.middleware.RateLimitHeaderMiddleware",
        "api.middleware.AuditMiddleware",
    ]

    ROOT_URLCONF = "config.urls"

    TEMPLATES = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": [],
            "APP_DIRS": True,
            "OPTIONS": {
                "context_processors": [
                    "django.template.context_processors.debug",
                    "django.template.context_processors.request",
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                ],
            },
        },
    ]

    WSGI_APPLICATION = "config.wsgi.application"

    # Redis settings for caching and rate limiting

    REDIS_HOST = env("REDIS_HOST", default="localhost")
    REDIS_PORT = env("REDIS_PORT", default=6379)
    REDIS_DB = env("REDIS_DB", default=0)
    REDIS_PASSWORD = env("REDIS_PASSWORD", default=None)

    CELERY_BROKER_URL = "redis://localhost:6379/0"
    CELERY_ACCEPT_CONTENT = ["json"]
    CELERY_TASK_SERIALIZER = "json"
    CELERY_RESULT_SERIALIZER = "json"
    CELERY_TIMEZONE = "Europe/London"

    # Logging configurations

    LOG_DIR = BASE_DIR / "logs"

    LOG_DIR.mkdir(exist_ok=True)

    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "[{levelname}] {asctime} [{name}] {module}.{funcName}:{lineno} - {message}",
                "style": "{",
                "datefmt": "%Y-%m-%d %H:%M:%S",
            },
            "simple": {
                "format": "[{levelname}] {asctime} - {message}",
                "style": "{",
                "datefmt": "%Y-%m-%d %H:%M:%S",
            },
            "detailed": {
                "format": "[{levelname}] {asctime} [{name}] PID:{process:d} Thread:{thread:d} - {message}",
                "style": "{",
                "datefmt": "%Y-%m-%d %H:%M:%S",
            },
        },
        "filters": {
            "require_debug_true": {
                "()": "django.utils.log.RequireDebugTrue",
            },
            "require_debug_false": {
                "()": "django.utils.log.RequireDebugFalse",
            },
        },
        "handlers": {
            # Console handler - for development
            "console": {
                "level": "DEBUG",
                "class": "logging.StreamHandler",
                "formatter": "simple",
                "filters": ["require_debug_true"],
            },
            # Console handler - for production
            "console_production": {
                "level": "INFO",
                "class": "logging.StreamHandler",
                "formatter": "verbose",
                "filters": ["require_debug_false"],
            },
            # General application log
            "app_file": {
                "level": "INFO",
                "class": "logging.handlers.RotatingFileHandler",
                "filename": LOG_DIR / "app.log",
                "maxBytes": 1024 * 1024 * 20,  # 20MB
                "backupCount": 10,
                "formatter": "verbose",
                "encoding": "utf-8",
            },
            # Error log - captures ERROR and CRITICAL only
            "error_file": {
                "level": "ERROR",
                "class": "logging.handlers.RotatingFileHandler",
                "filename": LOG_DIR / "errors.log",
                "maxBytes": 1024 * 1024 * 20,  # 20MB
                "backupCount": 10,
                "formatter": "detailed",
                "encoding": "utf-8",
            },
            # Debug log - everything, only in development
            "debug_file": {
                "level": "DEBUG",
                "class": "logging.handlers.RotatingFileHandler",
                "filename": LOG_DIR / "debug.log",
                "maxBytes": 1024 * 1024 * 50,  # 50MB
                "backupCount": 5,
                "formatter": "detailed",
                "filters": ["require_debug_true"],
                "encoding": "utf-8",
            },
            # Security-related log
            "security_file": {
                "level": "WARNING",
                "class": "logging.handlers.RotatingFileHandler",
                "filename": LOG_DIR / "security.log",
                "maxBytes": 1024 * 1024 * 10,  # 10MB
                "backupCount": 10,
                "formatter": "detailed",
                "encoding": "utf-8",
            },
            # Database queries log (useful for optimization)
            "db_file": {
                "level": "DEBUG",
                "class": "logging.handlers.RotatingFileHandler",
                "filename": LOG_DIR / "database.log",
                "maxBytes": 1024 * 1024 * 30,  # 30MB
                "backupCount": 5,
                "formatter": "verbose",
                "filters": ["require_debug_true"],
                "encoding": "utf-8",
            },
            # Mail admins on critical errors (production only)
            "mail_admins": {
                "level": "ERROR",
                "class": "django.utils.log.AdminEmailHandler",
                "filters": ["require_debug_false"],
                "formatter": "detailed",
            },
        },
        "loggers": {
            # Django's core loggers
            "django": {
                "handlers": ["console", "console_production", "app_file"],
                "level": "INFO",
                "propagate": False,
            },
            # Django request/response cycle
            "django.request": {
                "handlers": [
                    "error_file",
                    "mail_admins",
                    "console",
                    "console_production",
                ],
                "level": "ERROR",
                "propagate": False,
            },
            # Django security
            "django.security": {
                "handlers": ["security_file", "console", "console_production"],
                "level": "WARNING",
                "propagate": False,
            },
            # Database queries
            "django.db.backends": {
                "handlers": ["db_file"],
                "level": "DEBUG",
                "propagate": False,
            },
            # Django server
            "django.server": {
                "handlers": ["console", "console_production", "app_file"],
                "level": "INFO",
                "propagate": False,
            },
            # All your app code (services, views, models, etc.)
            # This catches everything in your project automatically
            "": {  # Empty string = root logger for your app
                "handlers": [
                    "console",
                    "console_production",
                    "app_file",
                    "error_file",
                    "debug_file",
                ],
                "level": "DEBUG" if DEBUG else "INFO",
            },
        },
        # Root logger - fallback for anything not caught above
        "root": {
            "handlers": ["console", "console_production", "app_file", "error_file"],
            "level": "INFO",
        },
    }

    # Database
    # https://docs.djangoproject.com/en/5.0/ref/settings/#databases

    CACHE = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
        }
    }

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env("DATABASE_NAME"),
            "USER": env("DATABASE_USER"),
            "PASSWORD": env("DATABASE_PASSWORD"),
            "HOST": env("DATABASE_HOST"),
            "PORT": env("DATABASE_PORT"),
        }
    }

    if not DEBUG:
        DJOSER = {
            "TOKEN_MODEL": None,
            "SEND_ACTIVATION_EMAIL": False,
            "SERIALIZER": {
                "user_create": "api.custom_auth.serializer.CustomUserCreateSerializer",
                "user": "api.custom_auth.serializer.CustomUserSerializer",
            },
        }

    REST_FRAMEWORK = {
        "DEFAULT_THROTTLE_CLASSES": [
            "api.throttling.IPRateThrottle",
            "api.throttling.UserRateThrottle",
        ],
        "DEFAULT_AUTHENTICATION_CLASSES": (
            "api.custom_auth.authentication.CookieJWTAuthentication",
        ),
        "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    }
    SPECTACULAR_SETTINGS = {
        "TITLE": "URL Shortener",
        "DESCRIPTION": "Just a url shortener on steroids",
        "VERSION": "0.0.1",
        "SERVE_INCLUDE_SCHEMA": False,
        "SWAGGER_UI_DIST": "SIDECAR",
        "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
        "REDOC_DIST": "SIDECAR",
    }

    SIMPLE_JWT = {
        "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
        "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
        "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
        "AUTH_HEADER_TYPES": ("Bearer",),
        "ALGORITHM": "HS256",
        "SIGNING_KEY": SECRET_KEY,
        "TOKEN_OBTAIN_SERIALIZER": "api.custom_auth.serializer.CustomTokenObtainPairSerializer",
    }
    AUTH_USER_MODEL = "custom_auth.CustomUser"

    # Password validation
    # https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]

    # Internationalization
    # https://docs.djangoproject.com/en/5.0/topics/i18n/

    LANGUAGE_CODE = "en-us"

    TIME_ZONE = "UTC"

    USE_I18N = True

    USE_TZ = True

    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/5.0/howto/static-files/

    STATIC_URL = "static/"

    # Default primary key field type
    # https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

    DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
