# Generated by Django 5.2.8 on 2025-11-18 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hashed_ip', models.CharField(max_length=64)),
                ('referer', models.TextField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url.url')),
            ],
        ),
    ]
