# Generated by Django 5.2.8 on 2025-12-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("url", "0003_alter_url_created_at_alter_url_expiry_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="browser",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="device",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="geolocation",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="operating_system",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["url", "timestamp"], name="analytics_v_url_id_dbe851_idx"
            ),
        ),
    ]
