# Generated by Django 5.2.8 on 2025-11-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='referer',
            new_name='referrer',
        ),
    ]
