# Generated by Django 5.2.8 on 2025-12-24 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_alter_visit_browser_alter_visit_device_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visit",
            old_name="referrer",
            new_name="referer",
        ),
    ]
