# Generated by Django 5.2.8 on 2025-11-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_rename_referer_visit_referrer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='visit',
            name='browser',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='device',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='geolocation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='operating_system',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
