# Generated by Django 5.2.8 on 2025-11-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_remove_visit_user_agent_visit_browser_visit_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='new_visitor',
            field=models.BooleanField(default=True),
        ),
    ]
